#!/usr/bin/env bash
# Regenerate manifest/tools.json + manifest/tools.js from the AlertKick MCP
# server. Run from a checkout that has alertkick-mcp as a sibling, or set
# AKMCP_DIR. Commit the result; consumers vendor or install this package.
set -euo pipefail
here=$(cd "$(dirname "$0")/.." && pwd)
mcp=${AKMCP_DIR:-$here/../alertkick-mcp}
ver=$(git -C "$mcp" describe --tags --always 2>/dev/null || echo dev)
(cd "$mcp" && go run -ldflags "-X main.version=$ver" ./cmd/webmcp-manifest) > "$here/manifest/tools.json"
{
  echo "// Generated by scripts/build-manifest.sh from alertkick-mcp $ver. Do not edit."
  printf 'export default '
  cat "$here/manifest/tools.json"
  echo ';'
} > "$here/manifest/tools.js"
echo "manifest: $(node -e "console.log(require('$here/manifest/tools.json').tools.length)") tools from alertkick-mcp $ver"
